services:
  mosquitto:
    image: eclipse-mosquitto      # not putting a version means it automatically pulls the latest build (latest build might crash)
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto-docker/config:/mosquitto/config     # ./config  ->  host directory (relative to the docker-compose.yml)
                                                        # /mosquitto/config  ->  the directory inside the container to mount it
      - ./mosquitto-docker/data:/mosquitto/data
      - ./mosquitto-docker/log:/mosquitto/log

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}


  middleware:
    build:
      context: ./python_middleware
      dockerfile: Dockerfile
    container_name: middleware
    restart: unless-stopped
    depends_on:
      - mosquitto
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_TOPIC=${MQTT_TOPIC}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}


# docker-compose log -f
# see stream of logs as they appear

# To Start the Docker Containers:
# docker-compose build
# docker-compose up
# OR
# docker-compose up --build